spring:
  config:
    import:
      - application-sql.yml
---
spring:
  datasource:
    hikari:
      pool-name: HikariUserServiceConnection
      schema: user_schema
  main:
    allow-bean-definition-overriding: true

server:
  port: 9090