spring:
  main:
      allow-circular-references: true
  config:
    import:
      - application-sql.yml
---
spring:
  datasource:
    hikari:
      pool-name: HikariPostServiceConnection
      schema: post_schema

server:
  port: 9091
  servlet:
    context-path: /api/post-service