version: "3.7"
services:
  postgresql:
    hostname: postgresql-service
    container_name: postgresql-service
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=youngadessi"
      - "POSTGRES_HOST_AUTH_METHOD=md5"
    volumes:
      - youngadessi_postgresql_data:/var/lib/postgresql/data
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  youngadessi_postgresql_data: